/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdditionalServices: typeof import('./src/components/AdditionalServices.vue')['default']
    BlockAdvantages: typeof import('./src/components/BlockAdvantages.vue')['default']
    BlockClients: typeof import('./src/components/BlockClients.vue')['default']
    BlockContacts: typeof import('./src/components/BlockContacts.vue')['default']
    BlockFAQ: typeof import('./src/components/BlockFAQ.vue')['default']
    BlockInfo: typeof import('./src/components/BlockInfo.vue')['default']
    BlockIntro: typeof import('./src/components/BlockIntro.vue')['default']
    BlockPresentation: typeof import('./src/components/BlockPresentation.vue')['default']
    BlockPrices: typeof import('./src/components/BlockPrices.vue')['default']
    BlockPromo: typeof import('./src/components/BlockPromo.vue')['default']
    BlockRegistration: typeof import('./src/components/BlockRegistration.vue')['default']
    BlockRegistrationSteps: typeof import('./src/components/BlockRegistrationSteps.vue')['default']
    BlockReviews: typeof import('./src/components/BlockReviews.vue')['default']
    BlockWhy: typeof import('./src/components/BlockWhy.vue')['default']
    HeaderLink: typeof import('./src/components/HeaderLink.vue')['default']
    LCButton: typeof import('./src/components/LCButton.vue')['default']
    PriceCard: typeof import('./src/components/PriceCard.vue')['default']
    StringLink: typeof import('./src/components/StringLink.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
